//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_shop_mvc.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ShippingDetails
    {
        public int ID { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Addres { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string ZipCode { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string PaidAmount { get; set; }
        public Nullable<int> PaymentId { get; set; }
        public string PaymentType { get; set; }
    
        public virtual Tbl_Payment Tbl_Payment { get; set; }
        public virtual Tbl_User Tbl_User { get; set; }
    }
}
